services:
  - type: web
    name: maju_bersama
    runtime: ruby
    plan: free
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        value: d1372afa8cfafed81462985d6880104c
      - key: WEB_CONCURRENCY
        value: 2
