databases:
  - name: maju_bersama
    databaseName: maju_bersama
    user: maju_bersama
    plan: free

services:
  - type: web
    name: maju_bersama
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maju_bersama
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: d1372afa8cfafed81462985d6880104c
      - key: WEB_CONCURRENCY
        value: 2
