default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maju_bersama_development

test:
  <<: *default
  database: maju_bersama_test

production:
  <<: *default
  database: maju_bersama_production
  username: maju_bersama_user
  password: xPPWJuZ4EoAqfOzcqmVVeXgyfCP90XEi
  host: dpg-cr5s132j1k6c7398g5g0-a
  port: 5432
